---
title: "First Knit"
author: "Andrew Gligoriu Valladares"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
 I attended multiple High School's but the High School I graduated from was Pete Knight High School. Math was always a bit easier for me than English. The subject I did best in was History and Biology. 
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
   I have a windows laptop and I would say I am a 5-6 on the scale of knowing computers. My internet connection at home is very good. 

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I prefer my first name which is, Andrew.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   
 
I want to achieve finicial freedom. The subject in college that would be my greatest interest is the AFAB class. I am tryin to get my AFAB certification.



## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  I've only ever been to arizona and texas, I've never been out of country before. Some of the countries I want to go to are El Salvador and Brazil. The branch I would choose if I got drafted would be the army or military. 




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 I am taking Math 115 and I am aware that it only covers the base education requirment. I want to attain an A in this class.






  




